# YOU MUST COPY THIS CONFIG TO THE ROOT OF THE FILESYSTEM WHERE THE (MAIN) EXECUTABLE IS. KEEP THIS HERE FOR EXPERIMENTATION, VERSIONING, ETC.
# Server configurations
serverInfo:
  # Your server ID
  guildIDNumber: ""
  # WeatherAPI of openWeatherMap for your bot. Get yours at the webpage (its free)
  weatherAPIKey: ""
  # The token of the bot to run it. You get yours on the discord developer page when you add it to the server.
  serverToken: ""
  # The bot logo
  botLogo: "https://cdn.discordapp.com/avatars/877115622725672991/1b9e83cf7c9f29ed63de3364ed71b452.webp?size=160"
  # Bot name
  botName: "CleverFox"
  # Log level (0 - Trace, 1 - Debug, 2 - Info, 3 - Warn, 4 - Error, 5 - Fatal)
  logLevel: ""

# Various modules to enable or disable
modules:
  # Administration module includes: kick, ban, timeout, purgeUsers
  administration: false
  # Not used right now
  logging: false
  # Slovak lottery password fetcher.
  lottery: false
  # Game planning isn't functional currently.
  planning: false
  # openWeather command /weather
  weather: false
  # Message purging feature (separate from administration)
  purge: false
  # API for the COVID info for SVK
  COVIDSlovakInfo: false
  # Automatic channel unlocking (must specify ID above)
  timedChannelUnlock: false



# Admin roleID and mod roleID
roleAdmin:
  # AdminID of the administrator role (highest privilege)
  roleAdminID: ""
  # ModID of the Moderator role (lower privilege)
  roleModID: ""

# Trusted roleID and Channel
roleTrusted:
  # Trusted users are users who earn XP and have a reward role. If your server has none, leave blank. You can have a tiered list.
  # Lowest privilege role 1
  roleTrustedID1: ""
  # Mid privilege role 2
  roleTrustedID2: ""
  # Highest privilege role 3
  roleTrustedID3: ""
  # Special, manually assigned low privilege role 4
  roleTrustedID4: ""
  # Channel for your friends
  channelTrustedID: ""

# Service channels
channelLog:
  channelLogID: ""
  gamePlannedLog: ""





